#!/usr/bin/env python

from IORlib.ECL import unfmt_file
from datetime import datetime

#--------------------------------------------------------------------------------
def invert(alist):
#--------------------------------------------------------------------------------
    return [1/a for a in alist]

#--------------------------------------------------------------------------------
def convert(file=None, fra=None, til=None):
#--------------------------------------------------------------------------------
    print(f'  Converting {fra} -> {til}')
    start_time = datetime.now()
    n = 0
    for block in unfmt_file(file).blocks():
        if block.key() in fra:
            i = fra.index(block.key())
            block.replace(invert, key=til[i])
            n += 1
    print(f'  Replaced {n} blocks in {(datetime.now()-start_time).total_seconds():.3f} seconds')
    print()


######################################################################################

if __name__ == '__main__':
    import sys
    from argparse import ArgumentParser

    print()
    parser = ArgumentParser(description='Convert from 1/FVF* to FVF* (Formation Volume Factors) in Eclipse UNRST-files')
    parser.add_argument('file', help='Name of UNRST-file')
    args = vars(parser.parse_args())
    
    inv_fvf = ('1/FVFGAS','1/FVFOIL','1/FVFWAT')
    fvf     = ('FVFGAS','FVFOIL','FVFWAT')
    convert(file=args['file'], fra=inv_fvf, til=fvf )
