name: Build Workflow

on:
  workflow_dispatch:
#    inputs:
#    tags:
#    description: 'test build'
  # release:
  #   types: [ published ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download UPX
      run: curl.exe -LJO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-win64.zip
    - name: Unzip
      run: 7z x upx-3.96-win64.zip
    - name: Dir
      run: dir 
    # - uses: actions/checkout@v3
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.9'
    # - name: Prepare Python
    #   run: |
    #     python -m pip install --upgrade pip
    #     python -m pip install -r requirements.txt
    #     python -m pip install pyinstaller
    # - name: Compile
    #   run: .\compile_iorsim.bat
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: IORSim_GUI
    #     path: dist/IORSim_GUI.exe
