name: Build Workflow

on:
  workflow_dispatch:
    inputs:
    tags:
    description: 'test build'
  # release:
  #   types: [ published ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: |
        python -m pip install --upgrade pip
    - run: |
        python -m pip install -r requirements.txt
    - run: |
        python -m pip install pyinstaller
    - run: .\compile_iorsim.bat
    - uses: actions/upload-artifact@v3
      with:
        name: IORSim_GUI.exe
        path: .